---
apiVersion: v1
kind: Pod
metadata:
 name: tomcat-pod
 labels:
  author: intelliqit
  type: appserver
spec:
 containers:
  - name: mytomcat
    image: tomcat
    ports:
     - containerPort: 8080
       hostPort: 6060

...
