---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
 name: httpd-rs
 labels:
   author: intelliqit
   type: frontend
spec:
 replicas: 3
 selector:
  matchLabels:
   type: frontend
 template:
  metadata:
   name: httpd-pod
   labels:   
    type: frontend
  spec:
   containers:
    - name: appserver
      image: httpd
      ports:
       - containerPort: 80
         hostPort: 9999

